# Do NOT update manually; changes here will be overwritten by Copier
_commit: c26a26c
_src_path: gh:open-synergy/ssi-addons-repo-template
dependency_installation_mode: OCA
generate_requirements_txt: true
include_aeroo_report: false
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: ssi-l10n-indonesia-partner
repo_name: ssi-l10n-indonesia-partner
repo_slug: ssi-l10n-indonesia-partner
travis_apt_packages: []
travis_apt_sources: []

